import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#dcd9d9',
        'tertiary': '#735858',
        'on-error': '#ffffff',
        'on-secondary-fixed-variant': '#454747',
        'primary-fixed': '#ffdad7',
        'on-tertiary': '#ffffff',
        'inverse-primary': '#ffb3af',
        'on-surface': '#1b1c1c',
        'inverse-on-surface': '#f3f0f0',
        'surface-variant': '#e4e2e1',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-surface-variant': '#5a413f',
        'tertiary-fixed-dim': '#e1bebe',
        'outline-variant': '#e2bebc',
        'on-primary-container': '#63000c',
        'inverse-surface': '#303030',
        'surface-tint': '#b3272e',
        'secondary-fixed-dim': '#c6c6c7',
        'on-secondary-fixed': '#1a1c1c',
        'surface-container-low': '#f6f3f2',
        'surface-container-high': '#eae7e7',
        'on-secondary': '#ffffff',
        'surface': '#fcf9f8',
        'primary-fixed-dim': '#ffb3af',
        'on-tertiary-container': '#3e2829',
        'secondary': '#5d5f5f',
        'tertiary-fixed': '#ffdada',
        'secondary-container': '#dfe0e0',
        'on-primary-fixed-variant': '#910619',
        'on-tertiary-fixed-variant': '#594041',
        'error': '#ba1a1a',
        'secondary-fixed': '#e2e2e2',
        'on-background': '#1b1c1c',
        'primary': '#b3272e',
        'surface-container-highest': '#e4e2e1',
        'on-secondary-container': '#616363',
        'outline': '#8e706e',
        'tertiary-container': '#ae8e8e',
        'surface-bright': '#fcf9f8',
        'on-primary': '#ffffff',
        'surface-container': '#f0eded',
        'primary-container': '#ff5e5e',
        'on-tertiary-fixed': '#2a1617',
        'background': '#fcf9f8',
        'on-primary-fixed': '#410005',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
      },
      spacing: {
        'safe-margin': '20px',
        'xs': '8px',
        'gutter': '16px',
        'sm': '12px',
        'base': '4px',
        'md': '16px',
        'lg': '24px',
        '2xl': '48px',
        'xl': '32px',
      },
      fontFamily: {
        'title-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'label-bold': ['12px', { lineHeight: '16px', fontWeight: '700' }],
      },
      boxShadow: {
        'card': '0 4px 20px rgba(0, 0, 0, 0.05)',
        'bottom-nav': '0 -8px 30px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
export default config
